<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>R</string>
		<string>r</string>
		<string>s</string>
		<string>S</string>
		<string>Rprofile</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(\(\s*$|\{\s*$)</string>
	<key>foldingStopMarker</key>
	<string>(^\s*\)|^\s*\})</string>
	<key>keyEquivalent</key>
	<string>^~R</string>
	<key>name</key>
	<string>R Extended</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#roxygen</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.r</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.r</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage-type</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#parenthesis</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b([a-zA-Z0-9._:]*)\s*(&lt;-|=)\s*(?=(function)\s*(\())</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.r</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.r</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=\))</string>
			<key>name</key>
			<string>meta.function.r</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.r.support-function</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b([a-zA-Z._][a-zA-Z0-9._]*)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.r</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.function-call.arguments.r</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.r</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function-call.r</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function-call-parameter</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>constant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(pi|letters|LETTERS|month\.abb|month\.name)\b</string>
					<key>name</key>
					<string>support.constant.misc.r</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(TRUE|FALSE|NULL|NA|NA_integer_|NA_real_|NA_complex_|NA_character_|Inf|NaN)\b</string>
					<key>name</key>
					<string>constant.language.r</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
					<key>name</key>
					<string>constant.numeric.r</string>
				</dict>
			</array>
		</dict>
		<key>function</key>
		<dict>
			<key>begin</key>
			<string>\b(function)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.r</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.r</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.r</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function-parameter</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>function-parameter</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.r</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=\(|,|^)\s*([a-zA-Z._][a-zA-Z0-9._]*)(?=\s*(?:\)|=[^=]|,|\n))</string>
				</dict>
			</array>
		</dict>
		<key>function-call-parameter</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.r</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=\(|,|^)\s*([a-zA-Z._][a-zA-Z0-9._]*)\s*(?==[^=])</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(break|next|repeat|else|in)\b</string>
					<key>name</key>
					<string>keyword.control.r</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(ifelse|if|for|return|switch|while|invisible)\b(?=\s*\()</string>
					<key>name</key>
					<string>keyword.control.r</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\-|\+|\*|\/|%\/%|%%|%\*%|%in%|%o%|%x%|\^|:=|%between%|%chin%|%like%|%\+%|%\+replace%|%:%|%do%|%dopar%|%&gt;%|%&lt;&gt;%|%T&gt;%|%\$%)</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.r</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(=|&lt;-|&lt;&lt;-|-&gt;|-&gt;&gt;)</string>
					<key>name</key>
					<string>keyword.operator.assignment.r</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(==|!=|&lt;&gt;|&lt;|&gt;|&lt;=|&gt;=)</string>
					<key>name</key>
					<string>keyword.operator.comparison.r</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(!|&amp;{1,2}|[|]{1,2})</string>
					<key>name</key>
					<string>keyword.operator.logical.r</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\.\.\.|\$|:|\~|@)</string>
					<key>name</key>
					<string>keyword.other.r</string>
				</dict>
			</array>
		</dict>
		<key>parenthesis</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.r</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.r</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.r</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.r</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.r</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.r</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>roxygen</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(#&apos;)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.r</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>@[a-zA-Z0-9]+</string>
							<key>name</key>
							<string>keyword.other.r</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.r</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?&lt;=@param)\s*([^ ]+)</string>
							<key>name</key>
							<string>keyword.other.r</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>storage-type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(character|complex|double|expression|integer|list|logical|numeric|single|raw)\b(?=\s*\()</string>
					<key>name</key>
					<string>storage.type.r</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&apos;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.r</string>
						</dict>
					</dict>
					<key>end</key>
					<string>&apos;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.r</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.r</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.r</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&quot;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.r</string>
						</dict>
					</dict>
					<key>end</key>
					<string>&quot;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.r</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.r</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.r</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.r</string>
	<key>uuid</key>
	<string>B2E6B78D-6E70-11D9-A369-000D93B3A10A</string>
</dict>
</plist>
