<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cpp</string>
		<string>cxx</string>
		<string>c++</string>
		<string>C</string>
	</array>
	<key>firstLineMatch</key>
	<string>.*?Rcpp.*</string>
	<key>foldingStartMarker</key>
	<string>(?x)
		 /\*\*(?!\*)
		|^(?![^{]*?//|[^{]*?/\*(?!.*?\*/.*?\{)).*?\{\s*($|//|/\*(?!.*?\*/.*\S))
	</string>
	<key>foldingStopMarker</key>
	<string>(?&lt;!\*)\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~C</string>
	<key>name</key>
	<string>Rcpp</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.c</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.c++</string>
		</dict>
	</array>
	<key>repository</key>
	<dict/>
	<key>scopeName</key>
	<string>source.c++.rcpp</string>
	<key>uuid</key>
	<string>95547a60-c4f5-11e3-9c1a-0800200c9a66</string>
</dict>
</plist>
